### ISSUE TITLE
Cannot find "raw dataset" from link

### ISSUE THREAD

**Issue by keiohta** [3dlg-hcvc/OPD#1]
Hi authors, thank you for sharing great codes, and congrats on your ECCV acceptance!
I would like to reproduce the results, but could not find the link to the "raw dataset" in [README.md](https://github.com/3dlg-hcvc/OPD#visualization). So, could you update it so that we can visualize the results?
Thanks!

**Comment by Jianghanxiao** [comment]
Hi,

Thanks for pointing out the problem. Actually the dataset link is the same as above [data](https://aspis.cmpt.sfu.ca/projects/motionnet/opd/dataset/OPD/dataset.tar.gz) link in the readme or the data link in the project website. 

Sorry that I forget to update the data link in the visualization section. If you have any other questions, feel free to ask. Thanks for following our work!

**Comment by keiohta** [comment]
Hi @Jianghanxiao ,

Thanks for the reply! I'll use the above data link then.

**Comment by Jianghanxiao** [comment]
Hi,

I just have a test and both data links mentioned above work from my side. Can you try again?
