### ISSUE TITLE
Scene depth maps for OPD synthetic dataset

### ISSUE THREAD

**Issue by zubair-irshad** [3dlg-hcvc/OPD#7]
Hi @Jianghanxiao, 

Great work and thank you for releasing the dataset and code. Do you plan on releasing scene-centric depth for OPD synthetic dataset? For reference, we are interested in getting the scene level depths of synthetic scenes (similar to OPD's real-world depth maps shared below). Any pointers would be greatly appreciated, thank you! 

OPD Synthetic depth maps:
![depth_1](https://github.com/3dlg-hcvc/OPD/assets/32943733/32f81b89-69d0-4cf7-aeca-917bbba24173)
![depth_2](https://github.com/3dlg-hcvc/OPD/assets/32943733/b30c530c-4740-40c4-a3f8-b8fe1d8eed86)

OPD Real depth maps:
![depth_1](https://github.com/3dlg-hcvc/OPD/assets/32943733/58c852f2-644f-46da-965f-39170929c881)
![depth_2](https://github.com/3dlg-hcvc/OPD/assets/32943733/9c84dd92-b946-47cc-b30f-d21aeb762589)

**Comment by Jianghanxiao** [comment]
Hi, thanks for asking. For this project, for the synthetic data, we don't have a real "scene" around the object, therefore, we don't have the scene-level depth map for this. There can be multiple solutions:

**Comment by zubair-irshad** [comment]
Thanks for the prompt response. I will close this issue as my question is answered.
