### ISSUE TITLE
Does the datasets have 3D scale value?

### ISSUE THREAD

**Issue by NTNawshin** [3dlg-hcvc/OPD#9]
Hi,
Thank you for sharing your work. Does OPDSynth or OPDReal dataset provide 3D scales of the objects or movable parts? Can the 'diagonal' attributes be used in any way in this regard?

**Comment by Jianghanxiao** [comment]
Hi,
Thanks for asking.

The 'diagonal' attributes in these two datasets is the diagonal length of the object in its canonical pose (you can treat it as the tight bbx), you can treat this as the scale of the objects. For the OPDSynth, the original model is from the SAPIEN dataset, we don't apply other scales, but following the scale in the original SAPIEN dataset. You can get the 3D model to get other statistics you want, like the part scale or so. For the OPDReal, the RGBD and the camera parameters are offered, if you want the part scale, you can try projecting the parts into 3D to get the statistics you want.

**Comment by NTNawshin** [comment]
Thank you for your reply. I am closing the issue now.
